close all;
sn = 87129; %Random signal generated by last five digits of students number
nsamp = 8000;   %number of samples in vector
v = puzzle(sn,nsamp);    %generate random signal from puzzle function

%k=-4000:4000-1;     %creates time vector 
%plot(k,v)           %plots signal against time
%xlabel('time (s)')  %labels x-axis
%ylabel('amplitude') %labels y-axis
%xlim([-200 200])    %limits range of x-axis of figure plotted to screen

%exercise 2
N =4096;                  %set segment length
t=[-N/2:N/2-1]*nsamp/N;  %create time vector
v_length = 1:N;          %set segment length vector 
V=fft(v(v_length));      %finding DFT of v
V_shift = fftshift(V);   %find fftshift 
V_abs=abs(V_shift);      %find magnitude

subplot(2,1,1)          %create subplot
plot(abs(t),(20*log10(V_abs/length(V))))  %plot magnitude of DFT on decibel
                                          %scale
grid on                                   %turn on grid for plot
xlim([0 nsamp/2])                         %set limit of x-axis
xlabel('Frequency (Hz)')                       %label x-axis
ylabel('Power/Frequency (dB/Hz)')         %label y-axis
subplot(2,1,2)                            %create second subplot
periodogram(v,[],[],nsamp)                %plot periodogram

%exercise 3

